# Generated by Django 5.1.7 on 2025-04-02 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название карты')),
                ('description', models.TextField(verbose_name='Описание действия')),
                ('effect_type', models.CharField(max_length=50, verbose_name='Тип эффекта')),
                ('effect_data', models.JSONField(default=dict, verbose_name='Данные эффекта')),
            ],
            options={
                'verbose_name': 'Карта действия',
                'verbose_name_plural': 'Карты действий',
            },
        ),
        migrations.CreateModel(
            name='Catastrophe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название катастрофы')),
                ('description', models.TextField(verbose_name='Описание катастрофы')),
                ('cause', models.TextField(verbose_name='Причина катастрофы')),
                ('duration_months', models.IntegerField(verbose_name='Продолжительность (месяцев)')),
            ],
            options={
                'verbose_name': 'Катастрофа',
                'verbose_name_plural': 'Катастрофы',
            },
        ),
        migrations.CreateModel(
            name='CharacterAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('profession', 'Профессия'), ('health', 'Здоровье'), ('baggage', 'Багаж'), ('phobia', 'Фобия'), ('fact', 'Факт о персонаже')], max_length=20, verbose_name='Тип атрибута')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Дополнительное описание')),
            ],
            options={
                'verbose_name': 'Атрибут персонажа',
                'verbose_name_plural': 'Атрибуты персонажей',
            },
        ),
        migrations.CreateModel(
            name='GameConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название конфигурации')),
                ('config_type', models.CharField(max_length=50, verbose_name='Тип конфигурации')),
                ('data', models.JSONField(verbose_name='Данные конфигурации')),
            ],
            options={
                'verbose_name': 'Конфигурация игры',
                'verbose_name_plural': 'Конфигурации игры',
            },
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(default='53f6bb57', max_length=10, unique=True, verbose_name='ID комнаты')),
                ('name', models.CharField(max_length=100, verbose_name='Название комнаты')),
                ('max_players', models.IntegerField(default=12, verbose_name='Максимальное количество игроков')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание игроков'), ('in_progress', 'Игра идет'), ('finished', 'Игра завершена')], default='waiting', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('bunker_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Размер бункера')),
                ('bunker_supplies', models.TextField(blank=True, null=True, verbose_name='Запасы в бункере')),
                ('bunker_capacity', models.IntegerField(default=0, verbose_name='Вместимость бункера')),
                ('catastrophe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.catastrophe', verbose_name='Катастрофа')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Игровая комната',
                'verbose_name_plural': 'Игровые комнаты',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='game.gameroom', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чата',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_round', models.IntegerField(default=1, verbose_name='Текущий раунд')),
                ('clockwise', models.BooleanField(default=True, verbose_name='Направление хода (по часовой)')),
                ('current_player_index', models.IntegerField(default=0, verbose_name='Индекс текущего игрока')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('result', models.TextField(blank=True, null=True, verbose_name='Результат игры')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='game.gameroom', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Игровая сессия',
                'verbose_name_plural': 'Игровые сессии',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание'), ('ready', 'Готов'), ('playing', 'Играет'), ('eliminated', 'Исключен'), ('survived', 'Выжил')], default='waiting', max_length=20, verbose_name='Статус')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок хода')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('gender', models.CharField(blank=True, max_length=20, null=True, verbose_name='Пол')),
                ('child_free', models.BooleanField(default=False, verbose_name='Child free')),
                ('revealed_attributes', models.JSONField(default=list, verbose_name='Открытые атрибуты')),
                ('baggage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baggage_players', to='game.characterattribute', verbose_name='Багаж')),
                ('fact1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fact1_players', to='game.characterattribute', verbose_name='Факт 1')),
                ('fact2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fact2_players', to='game.characterattribute', verbose_name='Факт 2')),
                ('health', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_players', to='game.characterattribute', verbose_name='Здоровье')),
                ('phobia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phobia_players', to='game.characterattribute', verbose_name='Фобия')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profession_players', to='game.characterattribute', verbose_name='Профессия')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.gameroom', verbose_name='Комната')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'unique_together': {('user', 'room')},
            },
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reveal', 'Раскрытие атрибута'), ('vote', 'Голосование'), ('elimination', 'Исключение игрока'), ('action_card', 'Использование карты действия'), ('game_start', 'Начало игры'), ('game_end', 'Конец игры')], max_length=20, verbose_name='Тип события')),
                ('data', models.JSONField(default=dict, verbose_name='Данные события')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время события')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='game.gamesession', verbose_name='Сессия')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='game.player', verbose_name='Игрок')),
                ('target_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_events', to='game.player', verbose_name='Цель события')),
            ],
            options={
                'verbose_name': 'Игровое событие',
                'verbose_name_plural': 'Игровые события',
            },
        ),
        migrations.CreateModel(
            name='PlayerActionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=False, verbose_name='Использована')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.actioncard', verbose_name='Карта действия')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_cards', to='game.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Карта действия игрока',
                'verbose_name_plural': 'Карты действий игроков',
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='Никнейм')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль игрока',
                'verbose_name_plural': 'Профили игроков',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(verbose_name='Номер раунда')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время голосования')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='game.gamesession', verbose_name='Сессия')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='game.player', verbose_name='Цель голосования')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to='game.player', verbose_name='Голосующий')),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоса',
                'unique_together': {('session', 'round_number', 'voter')},
            },
        ),
    ]
