# Generated by Django 5.1.7 on 2025-04-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Название предмета')),
                ('description', models.TextField(verbose_name='Описание предмета')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('usefulness', models.IntegerField(verbose_name='Полезность')),
            ],
            options={
                'verbose_name': 'Багаж',
                'verbose_name_plural': 'Багаж',
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Название факта')),
                ('description', models.TextField(verbose_name='Описание факта')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('usefulness', models.IntegerField(verbose_name='Полезность')),
            ],
            options={
                'verbose_name': 'Факт',
                'verbose_name_plural': 'Факты',
            },
        ),
        migrations.CreateModel(
            name='HealthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Название состояния')),
                ('description', models.TextField(verbose_name='Описание состояния')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('survival_factor', models.IntegerField(verbose_name='Фактор выживания')),
            ],
            options={
                'verbose_name': 'Состояние здоровья',
                'verbose_name_plural': 'Состояния здоровья',
            },
        ),
        migrations.CreateModel(
            name='Phobia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Название фобии')),
                ('description', models.TextField(verbose_name='Описание фобии')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('impact', models.IntegerField(verbose_name='Влияние')),
            ],
            options={
                'verbose_name': 'Фобия',
                'verbose_name_plural': 'Фобии',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Название профессии')),
                ('description', models.TextField(verbose_name='Описание профессии')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('usefulness', models.IntegerField(verbose_name='Полезность')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='room_id',
            field=models.CharField(default='35b3cd45', max_length=10, unique=True, verbose_name='ID комнаты'),
        ),
    ]
