# Generated by Django 5.1.7 on 2025-04-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_baggage_fact_healthstate_phobia_profession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catastrophe',
            name='effects',
            field=models.JSONField(default=list, verbose_name='Эффекты катастрофы'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='room_id',
            field=models.CharField(default='5e306f81', max_length=10, unique=True, verbose_name='ID комнаты'),
        ),
    ]
