# Generated by Django 5.1.7 on 2025-04-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_catastrophe_effects_alter_gameroom_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='room_id',
            field=models.CharField(default='755c8bd0', max_length=10, unique=True, verbose_name='ID комнаты'),
        ),
    ]
